# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_plain_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(90, 90, 256, 91))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(90, 230, 256, 81))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(420, 90, 256, 91))
        self.txt_info.setObjectName("txt_info")
        self.txt_signature = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_signature.setGeometry(QtCore.QRect(420, 230, 256, 91))
        self.txt_signature.setObjectName("txt_signature")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(350, 20, 35, 41))
        self.label_title.setObjectName("label_title")
        self.label_cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.label_cipher_text.setGeometry(QtCore.QRect(10, 230, 35, 10))
        self.label_cipher_text.setObjectName("label_cipher_text")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(370, 100, 35, 10))
        self.label_info.setObjectName("label_info")
        self.label_signature = QtWidgets.QLabel(self.centralwidget)
        self.label_signature.setGeometry(QtCore.QRect(380, 240, 35, 10))
        self.label_signature.setObjectName("label_signature")
        self.label_plain_text = QtWidgets.QLabel(self.centralwidget)
        self.label_plain_text.setGeometry(QtCore.QRect(30, 100, 35, 10))
        self.label_plain_text.setObjectName("label_plain_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(90, 330, 56, 17))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(250, 330, 56, 17))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(450, 350, 56, 17))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(630, 350, 56, 17))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_generate_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_keys.setGeometry(QtCore.QRect(440, 50, 56, 17))
        self.btn_generate_keys.setObjectName("btn_generate_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_cipher_text.setText(_translate("MainWindow", "CipherText:"))
        self.label_info.setText(_translate("MainWindow", "Information:"))
        self.label_signature.setText(_translate("MainWindow", "Signature"))
        self.label_plain_text.setText(_translate("MainWindow", "Plain Text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_generate_keys.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
